version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your!Strong@Passw0rd
    ports: ["1433:1433"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
