-- Core tables (sadece iskelet; kolonlar doldurulacak)
CREATE TABLE IF NOT EXISTS dbo.sellers (id BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS dbo.products (id BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS dbo.orders (id BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS dbo.payments (id BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS dbo.ledger_transactions (id BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS dbo.ledger_postings (id BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS dbo.outbox_messages (id BIGINT NOT NULL PRIMARY KEY);
